//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectroReadtoDatabaseV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chem
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Kanban_NO { get; set; }
        public Nullable<int> Part_NO { get; set; }
        public string Part_Name { get; set; }
        public string Standards { get; set; }
        public Nullable<int> Standards_NO { get; set; }
        public string In { get; set; }
        public string C { get; set; }
        public string Si { get; set; }
        public string Mn { get; set; }
        public string P { get; set; }
        public string S { get; set; }
        public string Cr { get; set; }
        public string Mo { get; set; }
        public string Ni { get; set; }
        public string Al { get; set; }
        public string Co { get; set; }
        public string Cu { get; set; }
        public string Nb { get; set; }
        public string Ti { get; set; }
        public string V { get; set; }
        public string W { get; set; }
        public string Pb { get; set; }
        public string Sn { get; set; }
        public string Mg { get; set; }
        public string As { get; set; }
        public string Zr { get; set; }
        public string Bi { get; set; }
        public string Ca { get; set; }
        public string Ce { get; set; }
        public string Sb { get; set; }
        public string Te { get; set; }
        public string B { get; set; }
        public string Zn { get; set; }
        public string La { get; set; }
        public string Fe { get; set; }
    }
}
